env:
  node: true
  jest: true
extends:
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  project: './tsconfig.json'
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - 'prettier'
rules:
  '@typescript-eslint/interface-name-prefix': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/ban-ts-comment': 0
  prettier/prettier: ['error', { endOfLine: 'auto' }]
  no-console: 0
